api:
  github:
    initialUrl: https://api.github.com/orgs/{org}/repos
    organization: productboard
    pat: ${GITHUB_PAT}
schedule:
  fixedDelay: 86400000
## H2 Configuration
spring:
  h2:
    console:
      enabled: true
      path: /app-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:app-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true
