CREATE TABLE IF NOT EXISTS LANGUAGE
(
    NAME       VARCHAR(50) NOT NULL PRIMARY KEY,
    PERCENTAGE DOUBLE      NOT NULL
);
--populate initial test data
INSERT INTO LANGUAGE
VALUES ('Kotlin', 0.7);
INSERT INTO LANGUAGE
VALUES ('Typescript', 0.3);